name: pocketbase_helpers
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Yoeri-z/pocketbase_helpers

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  pocketbase: ^0.23.0
  http: ^1.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
