name: pocketbase_helpers
description: Utilities for using typed data together with pocketbase.
version: 0.0.2
repository: https://github.com/Yoeri-z/pocketbase_helpers

environment:
  sdk: ^3.7.2

dependencies:
  pocketbase: ^0.23.0
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
