name: pocketbase_helpers
description: Utilities for using typed data together with pocketbase.
version: 0.0.8
repository: https://github.com/Yoeri-z/pocketbase_helpers

environment:
  sdk: ^3.7.2

dependencies:
  pocketbase: ^0.23.0
  http: ^1.4.0

dev_dependencies:
  faker: ^2.2.0
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0

topics:
  - pocketbase
  - models